[package]
name = "twitferr"
version = "0.1.0"
authors = ["Jose Javier Tlacuilo Fuentes <tlacuilose@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.redis]
version = "*"
